version: '3.4'

services:

  MyReverieGateway:
    image: ${DOCKER_REGISTRY-}myreveriegateway
    container_name: myreveriegateway
    networks:
      - myreverienetwork
    build:
      context: .
      dockerfile: src/ApiGateways/MyReverieGateway/Dockerfile

  goals.api:
    image: ${DOCKER_REGISTRY-}goalsapi
    container_name: api
    networks:
      - myreverienetwork
    build:
      context: .
      dockerfile: src/Services/Goals/Goals.API/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    container_name: identity
    networks:
      - myreverienetwork
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    container_name: web
    networks:
      - myreverienetwork
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
    environment:
      - "Urls:goalUrl=http://api/1/goals"

networks:
  myreverienetwork:
    driver: bridge
